stages:
  - test
  - deploy

test:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip python-pygame
  - python -m unittest

staging:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=cicd-test-cesi --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=cicd-test-cesi-prod --api-key=$HEROKU_PRODUCTION_API_KEY
